### ISSUE TITLE
Failures do not log

### ISSUE THREAD

**Issue by micahboggs** [OneLogicalMyth/New-User#1]
When I'm running tests, the UserResults.csv only contains the successful user adds. it doesn't list the failures.

I think this has to do with using continue in the catch blocks prior to the code that outputs the logs.

i.e. on line 436, you have 

```
    #Output some basic details for reference
    $Out = '' | Select-Object Username, HomeDirectory, Password, Failures
    $Out.Username = $Username
    $Out.HomeDirectory = $HomeDirectory
    $Out.Password = $Password
    $Out.Failures = $Failures -join ';'
    $Out
```

But in the event of a failure, this never gets run because you have

```
   catch
    {
        #user failed to create
        Write-Error "Failed to create user '$Username' - $_"
        $Failures += $_.ToString()
        continue
    }
```

And the continue causes it to jump back to the start of the loop.

I don't know enough to figure out how to correct this on my own, other than copy/pasting the whole $Out code into each of the catch blocks just before the continue statement. Can you call another function from within a catch block?

**Comment by OneLogicalMyth** [comment]
Hi there, this is indeed a bug. I am about to release version 1.2 that will correct this.

A function would work in a catch however you would then still need to skip the creation of the users home folder and adding to the groups, as the account does not exist. So created a simple if statement to handle this.

Hopefully this will now sort the issue for you. :+1:
